### ISSUE TITLE
How well does this work with React Router v4?

### ISSUE THREAD

**Issue by PolyPik** [jfairbank/redux-saga-router#14]
Because even with react router v4 being a total rewrite, I want to know if there is a slim chance that this library might still have some compatibility with v4.

**Comment by jfairbank** [comment]
Hi, @PolyPik!

Sorry, I've honestly not had an opportunity to try RR4 much at all, so I can't guarantee that it will work with redux-saga-router right now. It largely depends on if the history object is still available in RR4. You're welcome to investigate and report your findings if you have time.

**Comment by olehreznichenko** [comment]
Working well
```javascript
import { takeLatest, put, all } from 'redux-saga/effects'
import { LOCATION_CHANGE } from 'react-router-redux'
import { matchPath } from 'react-router-dom'

export default function* listenRouter() {
	yield takeLatest(LOCATION_CHANGE, handleRoute)
}

function* handleRoute({ payload: { pathname } }) {
	if (matchPath(pathname, { path: '/news', exact: true })) {
	  yield put(action)
	}
}

import { all } from 'redux-saga/effects'

import listenRouter from './router'
import workerFetchNews from './news'

export default function* rootSaga() {
	yield all([listenRouter(), workerFetchNews()])
}
```

**Comment by visusnet** [comment]
React Router v4 is now mentioned in the README. I guess this issue can be closed.
