### ISSUE TITLE
Uncaught TypeError: Unable to read the 'string' property undefined in createLink (createLink.js: 56)

### ISSUE THREAD

**Issue by ghost** [jfairbank/redux-saga-router#18]
We use redux-saga-router in the project.

But, as soon as I'm going to use the links:

import PropTypes from 'prop-types' // to react this is now a separate library
export const Link = createLink (history);
...
<li> <Link to = "/ users"> Users </ Link> </ li>
<li> <Link to = "/ users / 1"> Specific User </ Link> </ li>

The library redux-saga-router begins to swear:
Uncaught TypeError: Unable to read the 'string' property undefined in createLink (createLink.js: 56)

This is because the developers first introduced the PropTypes into the reaction, and from 15.3.0 they took it to a separate library. And redux-saga-router does not know about this and is trying to perform a check:

Link.propTypes = {
to: _react.PropTypes.string.isRequired,
className: _react.PropTypes.string,
children: _react.PropTypes.any
};};

How to solve the problem without giving up the library?

**Comment by jfairbank** [comment]
For anyone checking, this has been fixed in v2.1.2. Now redux-saga-router imports `PropTypes` from `prop-types` if `PropTypes` is missing from the `React` object.
