### ISSUE TITLE
redux-saga effects not attached.

### ISSUE THREAD

**Issue by bongster** [jfairbank/redux-saga-router#34]
Hi. i'm daniel.
I have a question about it.

I got a some issue When i use redux-saga-router in my projects.

package dependencies version.
* redux-saga: ^1.1.1
* redux-saga-router: 2.2.0

when i follow the example configuration in README.md

i got a 
```
TypeError: Cannot read property 'call' of undefined
var call = exports.call = _reduxSaga.effects.call;
```

I thought that error using way for effects module are changed

```
BEFORE:
import {effects } from 'redux-saga';
AFTER:
import { call } from 'redux-saga/effects';
```
That means redux-saga-router does not support redux-saga 1.1.1 version?

if not support it, could i downgrade my saga version? or has other way for solving it?

**Comment by luistorres** [comment]
hi @bongster, yeah you either downgrade it or as a `hacky solution` you can point your package.json to the compiled version of my branch https://github.com/jfairbank/redux-saga-router/pull/29

**Comment by bongster** [comment]
> hi @bongster, yeah you either downgrade it or as a `hacky solution` you can point your package.json to the compiled version of my branch #29

Thank you so much. 
so `hacky solution` is add a `redux-saga-test-plan` package in my package.json. is this right?

**Comment by bongster** [comment]
> hi @bongster, yeah you either downgrade it or as a `hacky solution` you can point your package.json to the compiled version of my branch #29

i solve the problem by my self. thank you so much.!!

**Comment by bongster** [comment]
@luistorres  Can i ask something more not depend on this issue?

i add a your github repository in my package.json
```
    "redux-saga-router": "git+https://github.com/luistorres/redux-saga-router.git",
```

and i add `import { router } from 'redux-saga-router'` this line but has a issue 

```
not found a module named 'redux-saga-router'
```
so has any advice to me?

**Comment by luistorres** [comment]
@bongster Yes, TLDR: `"redux-saga-router": "luistorres/redux-saga-router#dist"`

What happens is that since my fork isn't a published node package, npm/yarn can't retrieve it and compile it, which is needed for it to work in your app. To solve this I created a `#dist` branch where I pushed also the compiled version and it can use directly.
